apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: dev-project
  namespace: argocd

spec:
  description: Development applications

  sourceRepos:
    - https://github.com/KaleeswarG25/gitops-demo.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: dev