apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: prod-project
  namespace: argocd

spec:
  description: Production applications

  sourceRepos:
    - https://github.com/KaleeswarG25/cc-gitops.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: prod