replicaCount: 2

image:
  repository: nginx
  tag: "1.27"

serviceAccount:
  # Tell Helm to skip generating a ServiceAccount resource for frontend
  create: false 
  
  # Tell the frontend Deployment to attach to the backend's ServiceAccount
  name: "backend-{{ .Values.global.environment | default "prod" }}"
