apiVersion: v1
kind: ConfigMap

metadata:
  name: argocd-rbac-cm
  namespace: argocd

data:

  policy.default: role:readonly

  policy.csv: |
    # Developer permissions

    p, role:developer, applications, get, dev-project/*, allow
    p, role:developer, applications, sync, dev-project/*, allow

    # Map the developers group to developer role

    g, developers, role:developer