apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudcart
  labels:
    app: cloudcart
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cloudcart
  template:
    metadata:
      labels:
        app: cloudcart
    spec:
      containers:
        - name: cloudcart
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80