apiVersion: v1
kind: Service
metadata:
  name: cloudcart
  labels:
    app: cloudcart
spec:
  type: {{ .Values.service.type }}
  selector:
    app: cloudcart
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP