apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: backend
  namespace: argocd

spec:

  generators:
    - list:
        elements:
          - app: backend
            chartPath: charts/backend/backend

          - app: frontend
            chartPath: charts/frontend/frontend
    - list:
        elements:
          - environment: dev
            namespace: dev

          - environment: staging
            namespace: staging

          - environment: prod
            namespace: prod

  template:

    metadata:
      name: '{{app}}-{{environment}}'

    spec:

      project: default

      source:
        repoURL: https://github.com/KaleeswarG25/cc-gitops.git
        targetRevision: main
        path: '{{chartPath}}'

        helm:
          valueFiles:
            - '../../../environments/{{environment}}/{{app}}-values.yaml'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true