apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backend
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - app: backend
                  chartPath: charts/backend/backend
                - app: frontend
                  chartPath: charts/frontend/frontend
          - list:
              elements:
                - environment: dev
                  namespace: dev
                  project: prod-project
                - environment: staging
                  namespace: staging
                  project: default
                - environment: prod
                  namespace: prod
                  project: prod-project
  template:
    metadata:
      name: '{{app}}-{{environment}}'
    spec:
      # Reverted to default to prevent MissingProject failures for staging
      project: {{project}} 
      source:
        repoURL: https://github.com/KaleeswarG25/cc-gitops.git
        targetRevision: main
        path: '{{chartPath}}'
        helm:
          valueFiles:
            # Matches your 3-level folder structure exactly
            - '../../../environments/{{environment}}/{{app}}-values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
